name: KillTracker
main: me.fisher2911.killtracker.KillTracker
version: 1.1.1
author: fisher2911
api-version: 1.16
softdepend:
  - PlaceholderAPI
  - MythicMobs
permissions:
  killtracker.menu:
    default: op
    description: Allows players to open the kill tracker menu
